---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: gallery
spec:
  encryptedData:
    .dockerconfigjson: AgBF7GLBjhSjeX+AKTO0U3A5J3MLL7Laka/NXtYMYv6Sl3CALHW7yM87+aEapcP69CPV6f5dvRWglZwclpek3OHozA4SS7khqEoWxJrbYUX6O2zTzE6AIYXdTNSJ6pEc33k99/HWctm3fDrgcRsB4UZUYvVGKb1y89Qs4J0M5iawOT8AEGF62ufVVWv5qqXwj+bzeXBqTAWRSzYQpvSsdfdZsJriSb8C62ofidZ2QZ+BJ0heajB6nDMligClOp/syNsLlmpJ+b2DAy+8BEdpShg5ojproU2sucQ+2jQuDjTIojVLUERfg6NKC2+0CS7ZidyVcYTVYZkifuZLbNYfQujV2U7WvjJH2O1kU6ydOQBqCMZukr2+uRZciTzDtlo7fg0kVfVLtxDcebOfHDaxmnWX241jHcDHuilIeLeH3hPlm98BFlDCKapAlwZXpkgQRHiCjTLmp4yAw0x56vnD70n6/pJDQ7N90Wh5D9h/OQ9kBvk4g1a8MFD3JaBeZfN2IqTZDTEBloNAZ3Omf3H8FqT3O+A4TBVb55roMJNzv8Jat7I1akRgH8wVUaQT8vEio6WyZzd+CwHOGXMKQV/gIPXS8C0gkOTR/lT3dhVO+OtR1NjnYzf1OmQU7VdY+3EFSa/B6ONgBW+uhu+ZoyOoTb46G2U2+/g9MwDPuFr1vApMEA2rHif4sr/gA3S524l034203NlC7tE7/RKeGglFRJm+6CKOVa0tRgXv4/LmmVevOzrf8HaZ62qrGXQFWNTIjCbshI1DCQZBvuyDkryQXHlq7cfvh8XUIdCHXuPqhEpD44NFUy/vGeX93vg3vHmegG02132eowFtPqtZsNURDss6c3ZtrU+Xo16qpHxsvJW7Zkmw4KYf+/nxbaVvH8VYgD49YR5p1NUopFpdCiSbfiBlb1WDZ5mncplhCrP7TxXurg47tqQ9tqrqFJ+DFN/OgDwzJa9GAZMqz2Pf+dzS53Sec9VFjmTeezGKV7pUSGxqL2ixmzeWgIYstYyz5SLwnZeA4dLiXPSBEXsxGINVMWlrSg==
  template:
    metadata:
      name: registry-credentials
      namespace: gallery
    type: kubernetes.io/dockerconfigjson
