---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secret
  namespace: gallery
spec:
  encryptedData:
    JWT_SECRET: AgCQ1F3Yf3xQnR7zTr32W7ghzR2MMApmoWMZr9RGI9D0yd1E2wJ+5HbGu45Ql4ZlE7S9844pVQ3gnVkgcl5hFdu9Py7gruX4hfJ/BcFX94fB9k0WxYTWNyBrNudH2bsRh2WmogkdsX9KMKmRSV8hOeiNn7gCpPqT/7e4xXwUk6NNF/jAebBPENadpVsys9P07wsdxA9o746ju/3jTEA5JTOS7L0edPiAGjL/NJ9sfTBlFXIVS+grq3Mi+6NRTanW8Y03dSznH7PMme1J33VG9GmkwheXsRtN5MzyIOP31iaxTf9++si1qxHux9mQ69woev05lQ6GRCfwR0B4iW2VKHf7RFk360bpbGmZ6r2bQNPEjJJPcHYu3e64LPex0OkSbsECJLDMQjLGZ9+vwTvtf2Be2sPLpfyqnwWnT2jwspaKVRygXioO4h3LcFgo5ZvAE9O1vYeoI1mAFipXI1O7Z3yWLVsUXh4w7urqarlHQbLnP3Cz5Rl9KvY10j5gE52FwSMmLTRDwTUVKaNZ+XI7do1nYtsjUIrO+PUiunRjJDNmA4TbmSoUdSwPFZzfpeaNLCSUmAh0b4AeLWSIZWXmn4Ef3OUCgJ7sln9bdWtF8rN9m4rI5j7xhe3Kx/EonfaUqiuvRwavv3YSGFJQdWfoV9wk7BVu3QX160RKIwOtEOtFTylqeyUuSorEDrE1KuY87xHYkc+1Pn1jJzOlS9sibs3gpKNIcRxDhcCqHdTyiceJyJ0YEUdvyM6rrEU5TCs6/NHXwR34+kermSzfmpy8RbxEqw==
  template:
    metadata:
      name: frontend-secret
      namespace: gallery
    type: Opaque
