# SEALED VALUE REQUIRED — run kubeseal against the boukingolts cluster.
#
# To generate:
#   kubectl create secret docker-registry registry-credentials -n gallery-backend \
#     --docker-server=registry.boukingolts.art \
#     --docker-username=... \
#     --docker-password=... \
#     --dry-run=client -o yaml | kubeseal -o yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: gallery-backend
spec:
  encryptedData:
    .dockerconfigjson: AgDVNDrlLMPElX87x3DvjaVMzKku7wdgI+1xcloX5bVbBzHqeS0U2XISk0mn7ouToecRa20jo/buSMtkP8J5GnGdHBzvtafT0cRFYOCsNBiHZia6Q+iz0HHwqGSCSPYzJhrsLHNezIBKaJH9ewTWlzw49ygTy7EPOEhEZvz6MG2rc0coCNak8G8ar457ar+nRizFxtFwkMOMsrnap3e5TEneiGmSD5/2ByDGTPo0pA0GZJ8qJJcWtTXi4eOqd5B0vaLIUKxSAREYq+iPWq+MMquL0/f7C4EPninkzzX2ZaW/pQ1N7el/5SEJMmuZUzVXq/DmH+jg+CSCJ+l1DXy1OcUKUhNd64fDrMvD3oT3N7J+pQPU/3yzRf5fuLBJu/e6OFMsFL6fKDkvYHGsLI3sZQdGDPHtuUfuUfHonHnLlezgwRRtkVzoPGypZvourtWYuiE0Xqg4zZRldKG8fSf+x/VCPgPCUv/x7/DgqfX4mteQQa+AHCNpZxJuFh3pda2J5HEETX7sfpojxtGcwEtqXq9slhrHrOioeEPBlkLLg4S89ufg0bERGzZtKJpZKVXOIslRhHA47uQXT5n2i78bhnVyfQvEZXfP3B6CLhCXuCNsBVqFrWj8v1k+2MrCduj/hTH0+K6KSpeheIQvufqksuZcCrGdT861rz+by+GyDPgMe34RB95IUGWyHjf7eHy4Mq4YtG7T6lFOXSKPPLlY+AL96FkL0xipEykHnJwmzh+eZfyVV7yyrG7YdIN5gYTt1fwHOWYNEE459+fWNOvMMG/0/bUNwzvXesvA1ZKHUCsu3XlZ85OIXoYR055V+eGteWe29I/LNP1kIZk/GxUDe0vAJwjkhHr51xT+kD3m1jSKgOoRje6rRk8vm0qv9wquyX+dMTycG4llUcBfWh2TnmRrL3J+6ys8DZwScaWLlFV6DNsfwulIyuIcY5+q2n5qehPb8n20GM8t+XVj8fu+N2nxiq7ImloTdHOT4+l50UO4CEVbEltWOfg0IYtMQzeecEPxlLDRdbvMMQXNhEuTcItSZg==
  template:
    metadata:
      name: registry-credentials
      namespace: gallery-backend
    type: kubernetes.io/dockerconfigjson
