---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: gallery
spec:
  encryptedData:
    .dockerconfigjson: AgBpIa+3uYIcy92cYTWvOFwmsFN9oFnoQEXzd2Bgvs0lJd36+KLISZqbYKforyh+BntiEdABoAnPHguu3Dwyxe85h2zAu6JTA3wYb/XF6gNvOPRNcwyKjzrXZ/aHtZkznRbPduBOiuIu1dHulwFBexJK4ecm3r9cAPTluV11iAPNEoxLWax5ueA4vQHWqgIWM1iBATioByz7m3NE/I+3NDmaC4ZYpoPY6b7AMJjx3goS3bGTAxe4wexLpM8CIi30jWn4tBcxRDHYP8RyUmCPOB7xQSkiRB1Ms6762+94vjb6uzqPS1WYKHBB9+MxpdInlZhRgdsZL4jkoKyG92Wy2Mv+DFuu55yhGFiGi+E+wUkxddbGttayFNp85fBFkaIijpNARhotqEL6aKsS3EUiaRxXNZZni7Fh0B5t8lHXqLgPo4+fAfUGq1wE+V1U41MrnJb9qwhBGCDkKGbaIjWkI2E9I4OMPzfv+j26jqcoPPHvRf37F4uA57/gLSVsFYVgTeXOJtjyxJYxBGvoozFrvGAXjf2nVRb6Ytiu49jVg8xhUcDj9HjzFXmgTGN7UBI7u1eLj6EDA7i5pIranQnHwwVYDZcQt3knjtqKuUak7/QI4HQ8aVetq5fePCPybLbRPL+K3RRsHDY6sZrwOAgHRJiPqNbr6VbRCBBMX9rmoJqaxMWT+dMGJ+PDE4Jsdv3EURV5EB4T3AIz0/vo1rm+ipAHHzni3J+zkBK1uVA6G9z7hFRSWAvhPZWph6xYENsvmW9U34vJcv8sWFH1b+P53cd2uNvMIxvplcWLMpaUNXODAgMxC1UMCI0+YUmGqgw3qWMujPaJjUrFlvhtD6rUMF5lu4oFFkVAGMqkwsRxtmqvGMBrsccxLgVJh6vpj9rnSHe3ZIz7EabRGX43LNATAGYVHjrmEJ4Ngm23GbkihrGzyUTxuO8EWPNJ2rqi0rVip3MiMHHzmiJxRS+szuQ2/MjtIeVd7moxs5lwEZxihepTmtlu/NrgOvM2pn9DZ425IxHedJKQIhDyJnDSkr+hGZnVAQ==
  template:
    metadata:
      name: registry-credentials
      namespace: gallery
    type: kubernetes.io/dockerconfigjson
