replicaCount: 1

image:
  repository: registry.boukingolts.art/gallery-backend
  # Updated automatically by Argo Workflows on each push to dev
  tag: "e8a493a"
  pullPolicy: Always

registry:
  enabled: true
  url: "registry.boukingolts.art"

service:
  type: ClusterIP
  port: 5000

ingress:
  host: staging.api.boukingolts.art

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
