---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: gallery-staging
spec:
  encryptedData:
    .dockerconfigjson: AgCuUopz1uzjyMC9LyWJ7hzRYTFOCnqMFqB8e4uQqnE6jQdaqzoksO519xfY+3M9gLq14Lcyln0wR9Widevq8D9J13uj4sE2tK2IL9XWpQvH+2PF4q21yirwmhMZT09MEY9tgnLIQFU6qTAnFIs0/vohfIg7i3Z06QZpSUSwCCeaASBPtvR38eX7U3ZWz5o2AygcVm5aXbemGt9XiVJIgVcPUHw79rSSDwUNe8i8Gcqx1I1bME44ckOIbWCmlObETHUtabA/5xmfa2vXgM42oXVMhrj06BbO+Qa1MqwCmURYbr/YzysQqsoDYGreZSR9VdDkRaF5URzNlCiN2/J7WOVfhUgt6BUDpJwwFWFGddkqCbpmA2eWJNVDUjFluJFXf5FxJKvMOXUAbazvl8YxsW9+ADvNUJ5/Ei3CIlYx0WJ4Mzh4geJmAa7JhckNcocPXW2YIlVGbq2ljaNefCbkdqGGoq7beMih3m/HUUTjbjUfEve7JvYqcmI0YSyN9rQ1WBk5B872K3UC9M7xiAjMMIPpVnQRNmFLiZFqmws3wXle1otPvDhElkcVQfG7pTKvdHcT9WUE9vWZesMKhRluo9oOhhEc9+8WdSzWJEGK8fiVzLioyA3SkmmCk2OUf3MTR3k2JsSenyFRiSzi8CleMyOLXJ14oKCA31EoYvfK1CjaYXTNrKvjbCcCyiux1I1ucA028mzhl1mrLEGUw6sSPrUoEaURTQ0/+xVLNznZ7rVmeHwITrN0e6hVRPEj047b5XoZTlNdSDP4K/RewX5L6J2Wox70ZKpzDbaU1+AZxm2Pg5HoyrAy86Lu2NJKy7YT8B4qfDhS/gObi3B2hWkoGd/eEickl+dvRO+9yHbCJCi+9Uq/PULIdenEh+Rq0HjFWxaG+X4ySc5EBW2tStmrlFAyYawwvcyQfMCrNuCYQriEWg8/5ek99bBnZZDA6tAUfYznmDe24I2Q/4iSX5fSVMyGB7B3X2YxcRFh1T6ZwLODhfelaHQLy2dsUc1t2WmGXnqGD7IWGdmB/Y2WzmPkUlJdgA==
  template:
    metadata:
      name: registry-credentials
      namespace: gallery-staging
    type: kubernetes.io/dockerconfigjson
