# SEALED VALUE REQUIRED — run kubeseal against the boukingolts cluster.
#
# To generate:
#   kubectl create secret docker-registry registry-credentials -n gallery-frontend-staging \
#     --docker-server=registry.boukingolts.art \
#     --docker-username=... \
#     --docker-password=... \
#     --dry-run=client -o yaml | kubeseal -o yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: gallery-frontend-staging
spec:
  encryptedData:
    .dockerconfigjson: AgBGL0xmeDwMYduo5yqbYXnRIn0H3C5M46/h22gpIKGp4/ei/yIFa+mE+WPGiqNT2yfr10DNuqCteEMMzMw/+RlpdK2EIoAE8XLkbiRzOPI+tPnggIhz/4Y8LwjIgRDbS1AiUI6jP4YwD2vfLevPcBzazDW2oR8SlWuiTgdXtpXLZ1ashRnbJWirKP5lboDcXJm8H3IDnqHfSPPfNnnqZoIK1Lr+J7ykreGTtiCRrUn5XbzFMjffm4U/7hg0A46ppdN6nxCA9189K+1dU9TloT3Y5a/eSEe1+CbhLRTnf6MvqWhmKavsAyalQsIEq6F8/kc43N4djRsX5uND4/4UQ6mEAOoIKXetf00FASZnp2WS8R9HmGzad/42rrfPEoaWBCraQ741x87I+0TvX+4re64V/dCdGp5/rU0iMn5TkzX39JiIf/fYaRaCIWCDQw0P/X0jLY1+qyWY5g9Gow3J267dNTY2V17xshA1ZMF0yGDi3YeoGxHg85quSfkoZJyRTQdEpLj6xmUe6/9Z7Q2Ttpv5mCNKBssJZu2UQUHQFMz7HrEY3TyokRo58SV+oyV0/eFmp0h8C9QXmo6dqJK61GEvFWKQi8bCEylPICHvKsfo4mRw7pfxSwOZrXbcW3De+mIQbBHhcJrNse+ns+aXYzMGHeUA8AukCEGbeXO5tyT1mrlVdQOS+lNAhBxmNMtHG4XAlDFM46QaTM8zddAqJrrFVKNjJnz5dufAnzAbDtIUyZe7I1RB8tkR/e7FtjMP64rtq9vZvAp7LJIKVQlSx/4km099OEfXauwkz6kfdypRw3XruyK8Mw/hcxC3q0keMxinXUnkX8B73EBKZiDgIYe8cPVrygBXmQSiomx82cc74mc76bz3fEdvFJqA0cn+RZOPCqI5ZQgEMdfzb75qf6klV2r6WZB5QOvwqQteWZVPdm1kTvAvS8oDCyPokquxVBIILU7NQb271a5GubOf5kVBHBCQlNQeL5suI7kPf5P5B83kG6qB+OOa6jQFoE/VSmGJyOAAxo7VBt2uj14XAydPRg==
  template:
    metadata:
      name: registry-credentials
      namespace: gallery-frontend-staging
    type: kubernetes.io/dockerconfigjson
