# SEALED VALUE REQUIRED — run kubeseal against the boukingolts cluster.
#
# To generate:
#   kubectl create secret docker-registry registry-credentials -n gallery-backend-staging \
#     --docker-server=registry.boukingolts.art \
#     --docker-username=... \
#     --docker-password=... \
#     --dry-run=client -o yaml | kubeseal -o yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: gallery-backend-staging
spec:
  encryptedData:
    .dockerconfigjson: AgAO8pXNQyY290IPmo3gggyuv28f2VP9gRZeZdF1KfpFd7YUduD4RkgF0PS3o2rbvDePtPm7W2wUH7aBNtSbBiT8nKla31FU/afZH1FIdMxenWN8/jn99fI6sQZAOJFevoA01gF9LDEeur63OTxfoPxydm8H9iFT+Df3raXLbEK0GOJAnzWcsedKBZIgR7MBrX3Fa+76oeRBM43+1eZGNnmwGp5thqvN7orRHdo7cvGEIAps7yXldP3iIBYvwgL1EtC7+VRB64SsyXV91Qzp4YPewLlzQkb2hcqKEIQfYqbKFZfjgZ/TaaSpSdjqwOCiRl5ieTMJ93fD1clKjI4+XQxz9Q103n3aaBrTUPUSFpCj9XDYxQMPxSfFUleS5psNpSb6GTMCtGQZxddz8FNWHeWXYZeWqA7UyUiocvynFsw4llXjsUgp7At5LbfW5XK2q4YKhR7dhXuVrLKefQ34Qckb/RzV4s/5kTqjzIxpE98AxaM8jv0vi8bVE+lWaNHYH/FnFrquZ+/jquacfO37rfhco1KOamQ1R+L8ylzS8Qz+QHq95z8iM2HDD2pdoAe+Qbna24xwkAgHvF2PzzcWtftOvOm1ohd99H+QIidK0hdaYLCitbjaHEvUyIvWQmvK17gP933x2BeSe4w5XvKtrKYa8VsA4RfQWHCgIDX9uqZN0uUwGUzDbD26WnqqtASB5GRQ8vs5hIJH9fpnAY0jcIJoo5a2FJdBZjEaG5VsrdpOkc94YIF9aI8F6CQHGYiUES21Ppfp0txz6o/V/jt+BP6mtTYb0S1jfzP8u8lc4CcYkdMNRRdaju71wu7XmiohbuYHirtGGrRfJGC74uTBeAmQtn1KLn6bAL8hMeyCQ74XcDlozk9n0cUEjNCMQ/zT5ECzYbmV2JgKjjrJIGcofQthgkaxMS8hR3QkdvhMQ2InVlAjbRUeWfteeE0z1SR1SXuBxbYwVmpbj0wAXAuNbn6PP6MUMRaetXMKf+VKdvXPmOKcDGPj69ss/o2Ul3rWM4N4aVIqg4jzo6Z1jQk5KS9Z9w==
  template:
    metadata:
      name: registry-credentials
      namespace: gallery-backend-staging
    type: kubernetes.io/dockerconfigjson
