---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: gallery-staging
spec:
  encryptedData:
    .dockerconfigjson: AgBWzJkQPLIUkuVth9o8QZHn3Qn+GhpkBh9R51IDZzEr+2C5+qm/jkYgYVF12fiiNsLfeDMvRbulp+QfyTSNtYeAJ78lr6XXUbddXby0l38eSAAKQiHgFZL6WZUr0K0k5aUjp7W1OZcwNrC/zesYHAgYr0N2iHnz9eW3SPYDBqObhU+zSG+gT75wlvhL6vPAkCUiBagZRPowLC2y7zfGchwyM4dnYf5sCatZn/5UsJmSnJjSZAfFJmB35gGDj/6K4IFXK1U+4stxVfZjtX2GPpmoH6TvUCAtzHMHoYw2n+g302YenxO6373VMD7lAXvNjOZUrmS/V92cYMDtefzAb6C7f5nMN8hZLRHTTeT8wfsCjeTGKXgzPMduuJ/+ZpGX1cCWP9lpMiBYFjsQuilyAzMI6hPWy7CGQgb4JstlYEWMQvdQgYoUsaD2PIH2wcslJhfnhGXzB5XolNIWBHPv9PA9QgDEQx/P/VyVDGFi8ljtwGpUDaD36OMYGRfCvEs112hMcjz0AM3WvTLIFPPzInyxIi1UaCqaheKfwuDBbDdwMiHN4EVRoRsw6d6RNAA+C3hbInjqjM/+qeH5402ZyZh3geygliim64xzwn1EiORdU23DOpjZVtNYAYGqEYmF5hKfTm92P9uF5bjeXGg6KPuzeLFBP/DXcQPcNAehhBl4IMXM/F4JNgh718dR3issdCZCDjIAfmYTn+0183LVvLRpQWk/Yb0vJiTLzwnrnCa80EZr4yCvqt1bDEcJSRnkDfFWVKgo7S9YSb/ZbCJjcuTWHbYtjoPq8fx/ccvRMQUxLR9YycDnDq1btQUo0oQaxJiplxF+cV2wej1Z45fOaHKzgqgY2+vWJokfczEZdUOYa8051EB9C0m5dBytmNDSJ0OJJnkieBuiPdQFaoF2spFkQ+7El5mCdrqmccTbgiDy3GYo/s6gOzN4XDE4TvsCRUrqeBMzyxbPazrMBQoZ+5/7SdNH+s/Pr9Z8m8UwaufJZ8VWb73tLZl4i+Y8YHaTO3eOtZcLlxNktXG9tO0j11+izA==
  template:
    metadata:
      name: registry-credentials
      namespace: gallery-staging
    type: kubernetes.io/dockerconfigjson
