replicaCount: 2

image:
  repository: registry.boukingolts.art/gallery-backend
  # Updated automatically by Argo Workflows on each push to main
  tag: "b7cc1c9"
  pullPolicy: Always

registry:
  enabled: true
  url: "registry.boukingolts.art"

service:
  type: ClusterIP
  port: 5000

ingress:
  host: api.boukingolts.art

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
